name: Rust Lint

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Install minimal nightly (for fmt)
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    
    - name: Install minimal stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - uses: actions/checkout@v6
    
    - uses: Swatinem/rust-cache@v2
      with:
        key: clippy
        cache-all-crates: false
        save-if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}
    
    - name: Check code formatting
      run: cargo +nightly fmt --all -- --check
    
    - name: Check cargo clippy warnings
      run: cargo clippy --workspace -- -D warnings
    
    - name: Check cargo clippy warnings for all targets
      run: cargo clippy --workspace --all-targets -- -D warnings
    
    - name: Check cargo clippy warnings for all targets and features
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

    - name: Clean after lint
      if: always()
      run: cargo clean

